FROM ioft/armhf-ubuntu:16.04
MAINTAINER Roger Stark <rho.ajax@gmail.com>

ENV NAME ocaml-4.04.0
WORKDIR /root

RUN apt-get -yqq update \
    && DEBIAN_FRONTEND=noninteractive apt-get -yqq --no-install-recommends install \
    wget pkg-config git build-essential m4 software-properties-common aspcud unzip rsync dialog libx11-dev \
    && apt-get -y update

RUN wget -t 3 -T 30 -nv http://caml.inria.fr/pub/distrib/ocaml-4.04/${NAME}.tar.gz \
    && tar xzf ${NAME}.tar.gz \
    && rm -f ${NAME}.tar.gz \
    && cd ${NAME} \
    && ./configure -prefix /usr \
    && make world.opt \
    && umask 022 \
    && make install \
    && make clean

RUN apt-get -yqq update \
    && DEBIAN_FRONTEND=noninteractive apt-get -yqq --no-install-recommends install opam 
    && sh -c '/bin/echo -e "y\n" | opam init' \
    && eval `opam config env`
